//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITProjectTryThree.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITProjectTryThree.Resources.Strings-en", typeof(Strings_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add item.
        /// </summary>
        internal static string sAddItem {
            get {
                return ResourceManager.GetString("sAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin panel.
        /// </summary>
        internal static string sAdminPanel {
            get {
                return ResourceManager.GetString("sAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to Collections.
        /// </summary>
        internal static string sBackToCollection {
            get {
                return ResourceManager.GetString("sBackToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BOOKS.
        /// </summary>
        internal static string sBook {
            get {
                return ResourceManager.GetString("sBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection.
        /// </summary>
        internal static string sCollection {
            get {
                return ResourceManager.GetString("sCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection Name.
        /// </summary>
        internal static string sCollectionName {
            get {
                return ResourceManager.GetString("sCollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collections.
        /// </summary>
        internal static string sCollections {
            get {
                return ResourceManager.GetString("sCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на collections.
        /// </summary>
        internal static string sCollectionsFound {
            get {
                return ResourceManager.GetString("sCollectionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection Type.
        /// </summary>
        internal static string sCollectionType {
            get {
                return ResourceManager.GetString("sCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To comment please log in.
        /// </summary>
        internal static string sCommentLogin {
            get {
                return ResourceManager.GetString("sCommentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments.
        /// </summary>
        internal static string sComments {
            get {
                return ResourceManager.GetString("sComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create your collection here!.
        /// </summary>
        internal static string sCreate {
            get {
                return ResourceManager.GetString("sCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string sCreate1 {
            get {
                return ResourceManager.GetString("sCreate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create collection.
        /// </summary>
        internal static string sCreateCollection {
            get {
                return ResourceManager.GetString("sCreateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To create please login.
        /// </summary>
        internal static string sCreateLogin {
            get {
                return ResourceManager.GetString("sCreateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new.
        /// </summary>
        internal static string sCreateNew {
            get {
                return ResourceManager.GetString("sCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creation date.
        /// </summary>
        internal static string sCreationDate {
            get {
                return ResourceManager.GetString("sCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string sDelete {
            get {
                return ResourceManager.GetString("sDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To delete please login.
        /// </summary>
        internal static string sDeleteLogin {
            get {
                return ResourceManager.GetString("sDeleteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string sDescription {
            get {
                return ResourceManager.GetString("sDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        internal static string sDetails {
            get {
                return ResourceManager.GetString("sDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string sEdit {
            get {
                return ResourceManager.GetString("sEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To edit please log in.
        /// </summary>
        internal static string sEditLogin {
            get {
                return ResourceManager.GetString("sEditLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на elements.
        /// </summary>
        internal static string sElementsFound {
            get {
                return ResourceManager.GetString("sElementsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string sFilter {
            get {
                return ResourceManager.GetString("sFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found.
        /// </summary>
        internal static string sFound {
            get {
                return ResourceManager.GetString("sFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GAMES.
        /// </summary>
        internal static string sGames {
            get {
                return ResourceManager.GetString("sGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello.
        /// </summary>
        internal static string sHello {
            get {
                return ResourceManager.GetString("sHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide otpional parameters.
        /// </summary>
        internal static string sHide {
            get {
                return ResourceManager.GetString("sHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        internal static string sHome {
            get {
                return ResourceManager.GetString("sHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        internal static string sImage {
            get {
                return ResourceManager.GetString("sImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item Details.
        /// </summary>
        internal static string sItemDetails {
            get {
                return ResourceManager.GetString("sItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 newly created Items.
        /// </summary>
        internal static string sItems {
            get {
                return ResourceManager.GetString("sItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items.
        /// </summary>
        internal static string sItemsList {
            get {
                return ResourceManager.GetString("sItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create ticket in JIRA.
        /// </summary>
        internal static string sJiraTicket {
            get {
                return ResourceManager.GetString("sJiraTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Like it?.
        /// </summary>
        internal static string sLikeIt {
            get {
                return ResourceManager.GetString("sLikeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To like please log in.
        /// </summary>
        internal static string sLikeLogin {
            get {
                return ResourceManager.GetString("sLikeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string sLogin {
            get {
                return ResourceManager.GetString("sLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string sLoginAction {
            get {
                return ResourceManager.GetString("sLoginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        internal static string sLogout {
            get {
                return ResourceManager.GetString("sLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MOVIES.
        /// </summary>
        internal static string sMovies {
            get {
                return ResourceManager.GetString("sMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MUSIC.
        /// </summary>
        internal static string sMusic {
            get {
                return ResourceManager.GetString("sMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Page.
        /// </summary>
        internal static string sMyPage {
            get {
                return ResourceManager.GetString("sMyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 newly created Collections.
        /// </summary>
        internal static string sNewly {
            get {
                return ResourceManager.GetString("sNewly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No collections yet.
        /// </summary>
        internal static string sNoCollectionsYet {
            get {
                return ResourceManager.GetString("sNoCollectionsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No items yet.
        /// </summary>
        internal static string sNoItemsYet {
            get {
                return ResourceManager.GetString("sNoItemsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It looks like you are not the owner of this collection.
        /// </summary>
        internal static string sNotOwner {
            get {
                return ResourceManager.GetString("sNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional checkbox.
        /// </summary>
        internal static string sOptionalCheckbox {
            get {
                return ResourceManager.GetString("sOptionalCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional checkbox.
        /// </summary>
        internal static string sOptionalCheckboxForTable {
            get {
                return ResourceManager.GetString("sOptionalCheckboxForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional checkbox name.
        /// </summary>
        internal static string sOptionalCheckboxName {
            get {
                return ResourceManager.GetString("sOptionalCheckboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional number.
        /// </summary>
        internal static string sOptionalNumber {
            get {
                return ResourceManager.GetString("sOptionalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional number.
        /// </summary>
        internal static string sOptionalNumberForTable {
            get {
                return ResourceManager.GetString("sOptionalNumberForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional number name.
        /// </summary>
        internal static string sOptionalNumberName {
            get {
                return ResourceManager.GetString("sOptionalNumberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional text.
        /// </summary>
        internal static string sOptionalText {
            get {
                return ResourceManager.GetString("sOptionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional text.
        /// </summary>
        internal static string sOptionalTextForTable {
            get {
                return ResourceManager.GetString("sOptionalTextForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Optional text name.
        /// </summary>
        internal static string sOptionalTextName {
            get {
                return ResourceManager.GetString("sOptionalTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Owner.
        /// </summary>
        internal static string sOwner {
            get {
                return ResourceManager.GetString("sOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        internal static string sProfile {
            get {
                return ResourceManager.GetString("sProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        internal static string sRegister {
            get {
                return ResourceManager.GetString("sRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        internal static string sRegistration {
            get {
                return ResourceManager.GetString("sRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role.
        /// </summary>
        internal static string sRole {
            get {
                return ResourceManager.GetString("sRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string sSearch {
            get {
                return ResourceManager.GetString("sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search results.
        /// </summary>
        internal static string sSearchResults {
            get {
                return ResourceManager.GetString("sSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Message.
        /// </summary>
        internal static string sSendMessage {
            get {
                return ResourceManager.GetString("sSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (separated by commas).
        /// </summary>
        internal static string sSep {
            get {
                return ResourceManager.GetString("sSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SOFT.
        /// </summary>
        internal static string sSoft {
            get {
                return ResourceManager.GetString("sSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string sStatus {
            get {
                return ResourceManager.GetString("sStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete this?.
        /// </summary>
        internal static string sSure {
            get {
                return ResourceManager.GetString("sSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tags.
        /// </summary>
        internal static string sTags {
            get {
                return ResourceManager.GetString("sTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string sTitle {
            get {
                return ResourceManager.GetString("sTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string sType {
            get {
                return ResourceManager.GetString("sType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        internal static string sUsername {
            get {
                return ResourceManager.GetString("sUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        internal static string sUsers {
            get {
                return ResourceManager.GetString("sUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        internal static string sView {
            get {
                return ResourceManager.GetString("sView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wanna create some collections?.
        /// </summary>
        internal static string sWanna {
            get {
                return ResourceManager.GetString("sWanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your collections:.
        /// </summary>
        internal static string sYourCollections {
            get {
                return ResourceManager.GetString("sYourCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Comment.
        /// </summary>
        internal static string sYourComment {
            get {
                return ResourceManager.GetString("sYourComment", resourceCulture);
            }
        }
    }
}
