//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITProjectTryThree.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITProjectTryThree.Resources.Strings-ru", typeof(Strings_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string sAddItem {
            get {
                return ResourceManager.GetString("sAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель администратора.
        /// </summary>
        internal static string sAdminPanel {
            get {
                return ResourceManager.GetString("sAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад к коллекциям.
        /// </summary>
        internal static string sBackToCollection {
            get {
                return ResourceManager.GetString("sBackToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КНИГИ.
        /// </summary>
        internal static string sBook {
            get {
                return ResourceManager.GetString("sBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коллекция.
        /// </summary>
        internal static string sCollection {
            get {
                return ResourceManager.GetString("sCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название коллекции.
        /// </summary>
        internal static string sCollectionName {
            get {
                return ResourceManager.GetString("sCollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коллекции.
        /// </summary>
        internal static string sCollections {
            get {
                return ResourceManager.GetString("sCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на коллекций.
        /// </summary>
        internal static string sCollectionsFound {
            get {
                return ResourceManager.GetString("sCollectionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип коллекции.
        /// </summary>
        internal static string sCollectionType {
            get {
                return ResourceManager.GetString("sCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполните вход, чтобы оставить комментарий.
        /// </summary>
        internal static string sCommentLogin {
            get {
                return ResourceManager.GetString("sCommentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии.
        /// </summary>
        internal static string sComments {
            get {
                return ResourceManager.GetString("sComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создай свою коллекцию!.
        /// </summary>
        internal static string sCreate {
            get {
                return ResourceManager.GetString("sCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string sCreate1 {
            get {
                return ResourceManager.GetString("sCreate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать коллекцию.
        /// </summary>
        internal static string sCreateCollection {
            get {
                return ResourceManager.GetString("sCreateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполните вход, чтобы создать.
        /// </summary>
        internal static string sCreateLogin {
            get {
                return ResourceManager.GetString("sCreateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string sCreateNew {
            get {
                return ResourceManager.GetString("sCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата создания.
        /// </summary>
        internal static string sCreationDate {
            get {
                return ResourceManager.GetString("sCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string sDelete {
            get {
                return ResourceManager.GetString("sDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполните вход, чтобы удалить.
        /// </summary>
        internal static string sDeleteLogin {
            get {
                return ResourceManager.GetString("sDeleteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        internal static string sDescription {
            get {
                return ResourceManager.GetString("sDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали.
        /// </summary>
        internal static string sDetails {
            get {
                return ResourceManager.GetString("sDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ред..
        /// </summary>
        internal static string sEdit {
            get {
                return ResourceManager.GetString("sEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполните вход, чтобы редактировать.
        /// </summary>
        internal static string sEditLogin {
            get {
                return ResourceManager.GetString("sEditLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на элементов.
        /// </summary>
        internal static string sElementsFound {
            get {
                return ResourceManager.GetString("sElementsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        internal static string sFilter {
            get {
                return ResourceManager.GetString("sFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено.
        /// </summary>
        internal static string sFound {
            get {
                return ResourceManager.GetString("sFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИГРЫ.
        /// </summary>
        internal static string sGames {
            get {
                return ResourceManager.GetString("sGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет.
        /// </summary>
        internal static string sHello {
            get {
                return ResourceManager.GetString("sHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спрятать опциональные параметры.
        /// </summary>
        internal static string sHide {
            get {
                return ResourceManager.GetString("sHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домашняя.
        /// </summary>
        internal static string sHome {
            get {
                return ResourceManager.GetString("sHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение.
        /// </summary>
        internal static string sImage {
            get {
                return ResourceManager.GetString("sImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали элемента.
        /// </summary>
        internal static string sItemDetails {
            get {
                return ResourceManager.GetString("sItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 последних элементов.
        /// </summary>
        internal static string sItems {
            get {
                return ResourceManager.GetString("sItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементы.
        /// </summary>
        internal static string sItemsList {
            get {
                return ResourceManager.GetString("sItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать задачу в JIRA.
        /// </summary>
        internal static string sJiraTicket {
            get {
                return ResourceManager.GetString("sJiraTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нравится?.
        /// </summary>
        internal static string sLikeIt {
            get {
                return ResourceManager.GetString("sLikeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполните вход, чтобы отметить понравившееся.
        /// </summary>
        internal static string sLikeLogin {
            get {
                return ResourceManager.GetString("sLikeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        internal static string sLogin {
            get {
                return ResourceManager.GetString("sLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        internal static string sLoginAction {
            get {
                return ResourceManager.GetString("sLoginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        internal static string sLogout {
            get {
                return ResourceManager.GetString("sLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИЛЬМЫ.
        /// </summary>
        internal static string sMovies {
            get {
                return ResourceManager.GetString("sMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МУЗЫКА.
        /// </summary>
        internal static string sMusic {
            get {
                return ResourceManager.GetString("sMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моя страница.
        /// </summary>
        internal static string sMyPage {
            get {
                return ResourceManager.GetString("sMyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 последних коллекций.
        /// </summary>
        internal static string sNewly {
            get {
                return ResourceManager.GetString("sNewly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет коллекций.
        /// </summary>
        internal static string sNoCollectionsYet {
            get {
                return ResourceManager.GetString("sNoCollectionsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет элементов.
        /// </summary>
        internal static string sNoItemsYet {
            get {
                return ResourceManager.GetString("sNoItemsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Похоже, вы не владелец этой коллекции.
        /// </summary>
        internal static string sNotOwner {
            get {
                return ResourceManager.GetString("sNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опциональный флажок.
        /// </summary>
        internal static string sOptionalCheckbox {
            get {
                return ResourceManager.GetString("sOptionalCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опц. флажок.
        /// </summary>
        internal static string sOptionalCheckboxForTable {
            get {
                return ResourceManager.GetString("sOptionalCheckboxForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название опционального флажка.
        /// </summary>
        internal static string sOptionalCheckboxName {
            get {
                return ResourceManager.GetString("sOptionalCheckboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опциональное число.
        /// </summary>
        internal static string sOptionalNumber {
            get {
                return ResourceManager.GetString("sOptionalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опц. число.
        /// </summary>
        internal static string sOptionalNumberForTable {
            get {
                return ResourceManager.GetString("sOptionalNumberForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название опционального числа.
        /// </summary>
        internal static string sOptionalNumberName {
            get {
                return ResourceManager.GetString("sOptionalNumberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опциональный текст.
        /// </summary>
        internal static string sOptionalText {
            get {
                return ResourceManager.GetString("sOptionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опц. текст.
        /// </summary>
        internal static string sOptionalTextForTable {
            get {
                return ResourceManager.GetString("sOptionalTextForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название опционального текста.
        /// </summary>
        internal static string sOptionalTextName {
            get {
                return ResourceManager.GetString("sOptionalTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец.
        /// </summary>
        internal static string sOwner {
            get {
                return ResourceManager.GetString("sOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        internal static string sProfile {
            get {
                return ResourceManager.GetString("sProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string sRegister {
            get {
                return ResourceManager.GetString("sRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string sRegistration {
            get {
                return ResourceManager.GetString("sRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль.
        /// </summary>
        internal static string sRole {
            get {
                return ResourceManager.GetString("sRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        internal static string sSearch {
            get {
                return ResourceManager.GetString("sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты поиска.
        /// </summary>
        internal static string sSearchResults {
            get {
                return ResourceManager.GetString("sSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        internal static string sSendMessage {
            get {
                return ResourceManager.GetString("sSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (через запятую).
        /// </summary>
        internal static string sSep {
            get {
                return ResourceManager.GetString("sSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОГРАММЫ.
        /// </summary>
        internal static string sSoft {
            get {
                return ResourceManager.GetString("sSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string sStatus {
            get {
                return ResourceManager.GetString("sStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить это?.
        /// </summary>
        internal static string sSure {
            get {
                return ResourceManager.GetString("sSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тэги.
        /// </summary>
        internal static string sTags {
            get {
                return ResourceManager.GetString("sTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string sTitle {
            get {
                return ResourceManager.GetString("sTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        internal static string sType {
            get {
                return ResourceManager.GetString("sType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        internal static string sUsername {
            get {
                return ResourceManager.GetString("sUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        internal static string sUsers {
            get {
                return ResourceManager.GetString("sUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смотреть.
        /// </summary>
        internal static string sView {
            get {
                return ResourceManager.GetString("sView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создадим пару коллекций?.
        /// </summary>
        internal static string sWanna {
            get {
                return ResourceManager.GetString("sWanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваши коллекции:.
        /// </summary>
        internal static string sYourCollections {
            get {
                return ResourceManager.GetString("sYourCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш комментарий.
        /// </summary>
        internal static string sYourComment {
            get {
                return ResourceManager.GetString("sYourComment", resourceCulture);
            }
        }
    }
}
